package extcontext

// This file is generated by update.sh.

import "github.com/maxvalor/instancefactory/baseextcontext"

const BuildGOPATH = "/home/maxvalor/workspace/go"

func GetClassName() (name string) {
	return baseextcontext.GenerateClassNameByGOPATH(BuildGOPATH)
}
